### ISSUE TITLE
Schema mapping double check -

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-dev/DOI#9]
@neil-ices-dk to setup meeting to go through this

**Comment by HansMJ** [comment]
This is the latest version of metadata send to DataCite (DataCite schema). Two things needs to be corrected and one to be checked...

- [ ]  publicationYear should not be fixed at 2016, but should take the information from sharepoint (publication year)

- [ ] publisher should be ICES and not ICES publishing

- [ ] additionally we should check that Authers if any listed in sharepoint are being added to the metadata as <creators>

---------DataCite metadata download (what we send them)-----------

10.17895/ICES.PUB.4338  

<?xml version="1.0" encoding="UTF-8"?>

<resource xmlns="http://datacite.org/schema/kernel-4" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4/metadata.xsd">  
  <identifier identifierType="DOI">10.17895/ices.pub.4338</identifier>  
  <titles> 
    <title>Atlantic salmon from the Northeast Atlantic</title> 
  </titles>  
  <creators> 
    <creator> 
      <creatorName>ICES</creatorName>  
      <givenName>ICES</givenName>  
      <familyName>null</familyName>  
      <affiliation>ICES</affiliation> 
    </creator> 
  </creators>  
  <publisher>ICES publishing</publisher>  
  <publicationYear>2016</publicationYear>  
  <resourceType resourceTypeGeneral="Text">Text</resourceType> 
</resource>

**Comment by HansMJ** [comment]
This is what we decided in March (7/3):

1.	If ‘publication author’ is filled on sharepoint, this name/names will be transferred as DataCite creator (creator of resource). 
2.	If ‘publication author’ is not filled we will use ‘ICES’ as the DataCite creator
3.	The DataCite ‘publisher’ field will be changed from ‘ICES publishing’ to ‘ICES’ only
4.	Year will be picked up correctly from sharepoint
5.	Nas will look into the possibility of using the sharepoint metadata as landing page instead of the resource itself

Below are two examples one with authors from sharepoint and one without (ICES is then used). The core information we are sending to DataCite is highlighted. Here is how the example referencing ICES looks in a DataCite search: https://search.datacite.org/works/10.17895/ices.pub.3720.

As agreed in the past we are keeping the DataCite metadata to the minimum at present (mandatory fields only).

Best,
Nas and Hans

With Authors (sharepoint: http://www.ices.dk/sites/pub/Publication%20Reports/Forms/DispForm.aspx?ID=33816):
<identifier identifierType="DOI">10.17895/ICES.PUB.3285</identifier>
<titles>
                <title>Guidelines for determining polymer-water and polymer-polymer partition coefficients of organic compounds</title>
</titles>
<creators>
                <creator>
                                <creatorName>Kees Booij</creatorName>
                </creator>
                <creator>
                                <creatorName>Foppe Smedes</creatorName>
                </creator>
                <creator>
                                <creatorName>Ian J. Allan</creatorName>
                </creator>
</creators>
<publisher>ICES</publisher>
<publicationYear>2017</publicationYear>
<resourceType resourceTypeGeneral="Text">Text</resourceType>
</resource>

Without author (sharepoint: http://www.ices.dk/sites/pub/Publication%20Reports/Forms/DispForm.aspx?ID=34004):
<identifier identifierType="DOI">10.17895/ICES.PUB.3720</identifier>
<titles>
                <title>EU-Norway request to ICES on a long-term management strategy for Pandalus in Skagerrak and the Norwegian Deep</title>
</titles>
<creators>
                <creator>
                                <creatorName>ICES</creatorName>
                </creator>
</creators>
<publisher>ICES</publisher>
<publicationYear>2017</publicationYear>
<resourceType resourceTypeGeneral="Text">Text</resourceType>
</resource>

**Comment by HansMJ** [comment]
Hi Nas

I think we should only use the creatorName tag as in this example from DataCite https://schema.datacite.org/meta/kernel-4.0/example/datacite-example-dataset-v4.0.xml:

<creators>
   <creator>
      <creatorName>Ewen Bell, Annika Clement, Helen Dobby, …</creatorName>
   </creator>
<creators>

, so in our case we add them all in one string as one creator. A bit alternative, but it should do it.
Hans

**Comment by Nas-ICES-IT** [comment]
SharePoint Metadata 

http://www.ices.dk/sites/pub/_api/web/lists/getbytitle('Publication%20Reports')/items('34224')?$select=PublicationYear,Publication_x0020_Author0,AuthorId,Resource_x0020_Type,Title
